// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIBSfFKXkjtsP7ZM57z4iZ1U4aTydpYc4',
    appId: '1:956168166587:web:001564aeb19605250f1d9e',
    messagingSenderId: '956168166587',
    projectId: 'velo-phnom-penh',
    authDomain: 'velo-phnom-penh.firebaseapp.com',
    storageBucket: 'velo-phnom-penh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoku1AUuJ0BTyKuN0DygCErgP-yaaVlSA',
    appId: '1:956168166587:android:d8462cb9a4c671e20f1d9e',
    messagingSenderId: '956168166587',
    projectId: 'velo-phnom-penh',
    storageBucket: 'velo-phnom-penh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfxLj7EVCt0_UDFOUSXaK3aWiNSymtDs0',
    appId: '1:956168166587:ios:186db5a25b27b7200f1d9e',
    messagingSenderId: '956168166587',
    projectId: 'velo-phnom-penh',
    storageBucket: 'velo-phnom-penh.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfxLj7EVCt0_UDFOUSXaK3aWiNSymtDs0',
    appId: '1:956168166587:ios:186db5a25b27b7200f1d9e',
    messagingSenderId: '956168166587',
    projectId: 'velo-phnom-penh',
    storageBucket: 'velo-phnom-penh.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIBSfFKXkjtsP7ZM57z4iZ1U4aTydpYc4',
    appId: '1:956168166587:web:bf4ec08dc933a0c90f1d9e',
    messagingSenderId: '956168166587',
    projectId: 'velo-phnom-penh',
    authDomain: 'velo-phnom-penh.firebaseapp.com',
    storageBucket: 'velo-phnom-penh.firebasestorage.app',
  );
}
